name: Build and push native container image
description: Build and push native container image.

inputs:
  gh_token:
    description: GitHub token.
    required: true
  sonar_token:
    description: SonarCloud token.
    required: true
  release_version:
    description: Version tag to use with container image
    required: true
  skip_test:
    description: True to skip Maven's test execution
    required: false
    default: "false"
outputs:
  image:
    description: "Built image"
    value: ${{ steps.get-image.outputs.image }}

runs:
  using: composite
  steps:
    #
    # Execute unit-test + Calculate test coverage + SCA with Sonar.
    #
    - name: Execute unit-test + Calculate test coverage + SCA with Sonar
      if: ${{ inputs.skip_test }} != 'true'
      shell: bash
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      run: |
        ${{ runner.temp }}/maven/bin/mvn verify \
          -Pvalidate \
          -s ${{ runner.temp }}/settings.xml \
          --no-transfer-progress

    #
    # Build native executable.
    #
    - name: Build native executable
      shell: bash
      run: |
        ${{ runner.temp }}/maven/bin/mvn clean package \
          -Pnative \
          -Dmaven.test.skip=true \
          -Dquarkus.native.container-build=true \
          -Dquarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21@sha256:832c01753ebb631890a9302f989a66ae54424d41e1f09ba9a207d7d734a5acb5 \
          -s ${{ runner.temp }}/settings.xml \
          --no-transfer-progress

    #
    # Build container image.
    #
    - name: Build container image
      shell: bash
      env:
        RELEASE_VERSION: ${{ inputs.release_version }}
      run: |
        docker build \
          -f src/main/docker/Dockerfile.native-micro \
          -t ghcr.io/${{ github.repository }}:$RELEASE_VERSION \
          .

    #
    # Push container image.
    #
    - name: Push container image
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
      run: |
        echo "$GH_TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push -a ghcr.io/${{ github.repository }}

    #
    # Get container image with sha256.
    #
    - name: Get container image with sha256
      id: get-image
      shell: bash
      env:
        RELEASE_VERSION: ${{ inputs.release_version }}
      run: |
        temp=$(docker image inspect -f '{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}:$RELEASE_VERSION)
        echo "image=${temp/@/:$RELEASE_VERSION@}" >> $GITHUB_OUTPUT
