name: Setup Java Build Environment
description: Setup Java build environment, downloading and intalling JDK and Maven.
inputs:
  gh_user:
    description: GitHub username to download dependencies.
    required: true
  gh_token:
    description: GitHub token to download dependencies.
    required: true
runs:
  using: composite
  steps:
    #
    # Cache JDK.
    #
    - name: Cache JDK
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # 5.0.3
      id: cache-jdk
      with:
        key: OpenJDK25U-jdk_x64_linux_hotspot_25.0.3_9.tar.gz
        path: |
          ${{ runner.temp }}/jdk_setup.tar.gz
          ${{ runner.temp }}/jdk_setup.sha256

    #
    # Download JDK and verify its hash.
    #
    - name: Download JDK and verify its hash
      if: steps.cache-jdk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "69264a7a211bf5029830d07bc3370f879769d62ebc5b5488e90c9343a2da0e1f  ${{ runner.temp }}/jdk_setup.tar.gz" >> ${{ runner.temp }}/jdk_setup.sha256
        curl -L "https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.3%2B9/OpenJDK25U-jdk_x64_linux_hotspot_25.0.3_9.tar.gz" -o "${{ runner.temp }}/jdk_setup.tar.gz"
        sha256sum --check --status "${{ runner.temp }}/jdk_setup.sha256"

    #
    # Setup JDK.
    #
    - name: Setup JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # 5.2.0
      with:
        distribution: "jdkfile"
        jdkFile: "${{ runner.temp }}/jdk_setup.tar.gz"
        java-version: "25"
        cache: maven

    #
    # Cache Maven.
    #
    - name: Cache Maven
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # 5.0.3
      id: cache-maven
      with:
        key: apache-maven-3.9.15-bin.tar.gz
        path: |
          ${{ runner.temp }}/maven_setup.tar.gz
          ${{ runner.temp }}/maven_setup.sha512

    #
    # Download Maven and verify its hash.
    #
    - name: Download Maven and verify its hash
      if: steps.cache-maven.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "33d81e0ec785f0207e3e5e3ffb61863e1dca5784c15ac3fb5ff105f69cffbea484eb8d473ea60467a63f7b0570eef8622f2fed8eee96acbe668aa313391cddb3  ${{ runner.temp }}/maven_setup.tar.gz" >> ${{ runner.temp }}/maven_setup.sha512
        curl -L "https://archive.apache.org/dist/maven/maven-3/3.9.15/binaries/apache-maven-3.9.15-bin.tar.gz" -o "${{ runner.temp }}/maven_setup.tar.gz"
        sha512sum --check --status "${{ runner.temp }}/maven_setup.sha512"

    #
    # Setup Maven.
    #
    - name: Setup Maven
      shell: bash
      env:
        GH_USER: ${{ inputs.gh_user }}
        GH_TOKEN: ${{ inputs.gh_token }}
      run: |
        mkdir ${{ runner.temp }}/maven
        tar -xvf ${{ runner.temp }}/maven_setup.tar.gz -C ${{ runner.temp }}/maven --strip-components=1
        echo "<settings><servers><server><id>github</id><username></username><password>$GH_TOKEN</password></server></servers></settings>" >> ${{ runner.temp }}/settings.xml