name: Setup Java Build Environment
description: Setup Java build environment, downloading and intalling JDK and Maven.
inputs:
  gh_user:
    description: GitHub username to download dependencies.
    required: true
  gh_token:
    description: GitHub token to download dependencies.
    required: true
runs:
  using: composite
  steps:
    #
    # Cache JDK.
    #
    - name: Cache JDK
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # 4.3.0
      id: cache-jdk
      with:
        key: OpenJDK21U-jdk_x64_linux_hotspot_21.0.8_9.tar.gz
        path: |
          ${{ runner.temp }}/jdk_setup.tar.gz
          ${{ runner.temp }}/jdk_setup.sha256

    #
    # Download JDK and verify its hash.
    #
    - name: Download JDK and verify its hash
      if: steps.cache-jdk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "f2dc5418092c43003db8f9005c4a286e1c0104fea96ccdd49e8ebd037cac9219  ${{ runner.temp }}/jdk_setup.tar.gz" >> ${{ runner.temp }}/jdk_setup.sha256
        curl -L "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.8%2B9/OpenJDK21U-jdk_x64_linux_hotspot_21.0.8_9.tar.gz" -o "${{ runner.temp }}/jdk_setup.tar.gz"
        sha256sum --check --status "${{ runner.temp }}/jdk_setup.sha256"

    #
    # Setup JDK.
    #
    - name: Setup JDK
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # 5.0.0
      with:
        distribution: "jdkfile"
        jdkFile: "${{ runner.temp }}/jdk_setup.tar.gz"
        java-version: "21"
        cache: maven

    #
    # Cache Maven.
    #
    - name: Cache Maven
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # 4.3.0
      id: cache-maven
      with:
        key: apache-maven-3.9.11-bin.tar.gz
        path: |
          ${{ runner.temp }}/maven_setup.tar.gz
          ${{ runner.temp }}/maven_setup.sha512

    #
    # Download Maven and verify its hash.
    #
    - name: Download Maven and verify its hash
      if: steps.cache-maven.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "bcfe4fe305c962ace56ac7b5fc7a08b87d5abd8b7e89027ab251069faebee516b0ded8961445d6d91ec1985dfe30f8153268843c89aa392733d1a3ec956c9978  ${{ runner.temp }}/maven_setup.tar.gz" >> ${{ runner.temp }}/maven_setup.sha512
        curl -L "https://archive.apache.org/dist/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz" -o "${{ runner.temp }}/maven_setup.tar.gz"
        sha512sum --check --status "${{ runner.temp }}/maven_setup.sha512"

    #
    # Setup Maven.
    #
    - name: Setup Maven
      shell: bash
      env:
        GH_USER: ${{ inputs.gh_user }}
        GH_TOKEN: ${{ inputs.gh_token }}
      run: |
        mkdir ${{ runner.temp }}/maven
        tar -xvf ${{ runner.temp }}/maven_setup.tar.gz -C ${{ runner.temp }}/maven --strip-components=1
        echo "<settings><servers><server><id>github</id><username></username><password>$GH_TOKEN</password></server></servers></settings>" >> ${{ runner.temp }}/settings.xml