name: PR Validation
description: Validates a pull request.
inputs:
  gh_user:
    description: GitHub username.
    required: true
  gh_token:
    description: GitHub token.
    required: true
  sonar_token:
    description: SonarCloud token.
    required: true
runs:
  using: composite
  steps:
    - name: PR title validation
      uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # 6.1.1
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
      with:
        types: |
          docs
          refactor
          chore
          fix
          feat
          breaking
        requireScope: false
        subjectPattern: ^[A-Z].+$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          doesn't match the configured pattern. Please ensure that the subject
          starts with an uppercase character.
        wip: false

    - name: Setup Java Build Environment
      uses: pagopa/mil-actions/setup-java-build-env@372a6b1b566cf0973539b95bcc38a389aa35d5b6 # 1.3.0
      with:
        gh_user: ${{ inputs.gh_user }}
        gh_token: ${{ inputs.gh_token }}

    - name: Execute Maven verify with "validate" profile
      shell: bash
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      run: ${{ runner.temp }}/maven/bin/mvn verify -Pvalidate -s ${{ runner.temp }}/settings.xml --no-transfer-progress
